export const apiRoutes = {
  login: () => "/Auth/login",
  register: () => "/Auth/register",
  currentUser: () => "/Auth/currentUser",
  loginUserWithExternalService: () => "/Auth/loginWithExternalService",
  resetPassword: () => "/Auth/resetPassword",
  forgotPassword: () => "/Auth/forgotPassword",
  createEmpresa: () => "/api/Empresa/create",
  listEmpresas: () => "/api/Empresa",
  obtenerEmpresa: (id: number) => `/api/Empresa/${id}`,
  deleteEmpresas: () => `/api/Empresa/deletesById`,
  listOrCreateUsers: () => "/api/User",
  listarCategorias: () => "/api/Categoria",
  listarCategoriasDeEmpresa: (empresaId: number) =>
    `/api/Categoria/categorias-de-empresa?empresaId=${empresaId}`,
  crearProducto: () => "/api/Producto",
  updateProducto: () => "/api/Producto/updateProduct",
  listarMisProductosEmpresa: () => "/api/Producto/mis-productos",
  listarProductosByEmpresa: (empresaId: number) =>
    `/api/Producto/productos-empresa?empresaId=${empresaId}`,
  buscarProductosByEmpresa: (empresaId: number, query: string) =>
    `/api/Producto/buscar-productos?empresaId=${empresaId}&query=${query}`,
  productoById: (prodId: any) =>
    `/api/Producto/${prodId ? prodId : "[prodId]"}`,
  productosRelacionados: () =>
    `/api/Producto/relacionados`,
  deleteProductoById: (prodId: any) =>
    `/api/Producto/${prodId ? prodId : "[prodId]"}`,
  calificarProducto: () => "/api/Producto/calificarProducto",
  listarTiposIva: () => "/api/TipoIva",
  userById: (userId: string) => `/api/User/${userId}`,
  listarPickups: () => "/api/PickUp",
  pickupsByEmpresa: (empresaId: number) =>
    `/api/Pickup/listarByEmpresa?empresaId=${empresaId}`,

  tipoIVAById: (id: number) => `/api/TipoIva/${id}`,
  listOrCreateDepartamento: () => "/api/Departamento",
  departamentoById: (id: number) => `/api/Departamento/${id}`,
  listOrCreateCiudad: () => "/api/Ciudad",
  crearCategoria: () => "/api/Categoria",
  deleteCategorias: () => "/api/Categoria",
  ciudadById: (id: number) => `/api/Ciudad/${id}`,
  crearPickup: () => "api/PickUp",
  deletePickups: () => `/api/PickUp/deletesById`,
  listarReclamos: () => "api/Reclamo",
  cerrarReclamo: () => "api/Reclamo/cerrar-reclamo",
  listarEstadisticasSort: () => "/api/Estadisticas/sort",
  listarEstadisticasAdmin: () => "/api/Estadisticas/admin",
  listarEstadisticasEmpresa: () => "/api/Estadisticas/empresa",
  editLookAndFeel: () => "/api/Empresa/editLookAndFeel",
  listarDirecciones: () => "/api/User/listarDirecciones",
  agregarDireccion: () => "/api/User/agregarDireccion",
  modificarDireccion: () => "/api/User/modificarDireccion",
  agregarProductoCarrito: () => "/api/Carrito",
  borrarLinea: () => "/api/Carrito/borrarLinea",
  obtenerCarrito: (empresaId: any) => `/api/Carrito/obtenerCarrito?EmpresaId=${empresaId}`,
  listVentasByEmpresa: () =>  `/api/Empresa/ventas`,
  obtenerDetalleCompra : (id:number) =>  `/api/Compra/${id}`,
  getMisCompras: ()=>   `/api/Compra/listMyCompras`,
  efectuarCompra: () => "/api/Carrito/comprar",
  actualizarEstadoCompra: (id:number)=>  `/api/Compra/${id}/cambiarEstado`,
};
